package com.redhat.gss;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Card implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Card() {
    }




}